DROP TABLE IF EXISTS TAREA;

CREATE TABLE TAREA(
    IDENTIFICADOR INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(250) NOT NULL,
    FECHA_CREACION TIMESTAMP NOT NULL,
    VIGENTE BOOLEAN NOT NULL
);

